version: '3'
services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  backend:
   image: tools/launch-bay
   # optional port mapping (for swagger purpose) - ports: - _:_
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./env-configs-web
