PUT http://localhost:8193/api/v1.0/global_config
accept: application/json
Content-Type: application/json

{
  "envConf": [
    {
      "envKey": "POSTGRES_PORT",
      "type": "integer",
      "default": {
        "value": 5432
      },
      "envOverride": {
        "dev": {
          "value": 25432
        },
        "stage": {
          "value": 15432
        },
        "prod": null
      }
    },
    {
      "envKey": "PULSAR_HOST",
      "default": null,
      "type": "string",
      "envOverride": {
        "dev": {
          "value": "pulsar.dev"
        },
        "stage": {
          "value": "pulsar.stage"
        },
        "prod": {
          "value": "pulsar.prod"
        }
      }
    },
    {
      "envKey": "ZIPKIN_TRACE_LOGS",
      "type": "boolean",
      "default": {
        "value": true
      },
      "envOverride": {
        "dev": {
          "value": false
        },
        "stage": {
          "value": false
        },
        "prod": null
      }
    }
  ],
  "deployConf": [
    {
      "default": 1,
      "envOverride": null,
      "type": "replica"
    }
  ],
  "version": 0
}

###

