PUT http://localhost:8193/api/v1.0/global_config
accept: application/json
Content-Type: application/json

{
  "envConf": [
    {
      "envKey": "AEROSPIKE_SERVERS_DSP",
      "default": null,
      "envOverride": {
        "dev": {
          "value": "aerospike-us-east-1.gdpr-dev.demandbase.com"
        },
        "stage": {
          "value": "aerospike-us-east-1.stg.demandbase.com"
        },
        "prod": {
          "value": "aerospike-us-east-1.dsp.demandbase.com"
        }
      },
      "type": "string"
    },
    {
      "envKey": "AEROSPIKE_PORT_DSP",
      "default": {
        "value": 3000
      },
      "envOverride": {
        "dev": null,
        "stage": null,
        "prod": null
      },
      "type": "integer"
    }
  ],
  "deployConf": [],
  "version": 3
}

###

