POST http://localhost:8193/api/v1.0/project
accept: application/json
Content-Type: application/json

{
  "id": "anticor-liveramp",
  "name": "Anticor Liveramp",
  "envConf": [
    {
      "envKey": "LIVERAMP_DB_HOST",
      "default": null,
      "envOverride": {
        "dev": {
          "value": "pg-liveramp.dev"
        },
        "stage": {
          "value": "pg-liveramp.stage"
        },
        "prod": {
          "value": "pg-liveramp.prod"
        }
      },
      "type": "string"
    },
    {
      "envKey": "LIVERAMP_DB_PORT",
      "default": {
        "value": 5432
      },
      "envOverride": {
        "dev": null,
        "stage": null,
        "prod": null
      },
      "type": "integer"
    },
    {
      "envKey": "LIVERAMP_DB_SCHEMA",
      "default": {
        "value": "liveramp"
      },
      "envOverride": {
        "dev": null,
        "stage": null,
        "prod": null
      },
      "type": "string"
    },
    {
      "envKey": "LIVERAMP_DB_USER",
      "default": {
        "value": "liveramp"
      },
      "envOverride": {
        "dev": null,
        "stage": null,
        "prod": null
      },
      "type": "string"
    }
  ],
  "deployConf": [
    {
      "default": 1,
      "envOverride": null,
      "type": "replica"
    },
    {
      "default": 100,
      "envOverride": {
        "dev": 50,
        "stage": null,
        "prod": 200
      },
      "type": "request_cpu"
    },
    {
      "default": 1000,
      "envOverride": {
        "dev": 100,
        "stage": null,
        "prod": 2000
      },
      "type": "limit_cpu"
    },
    {
      "default": 512,
      "envOverride": {
        "dev": 256,
        "stage": null,
        "prod": 1024
      },
      "type": "request_ram"
    },
    {
      "default": 1024,
      "envOverride": {
        "dev": 512,
        "stage": null,
        "prod": 2048
      },
      "type": "request_lim"
    },
    {
      "default": "-Xms512M -Xmx1G",
      "envOverride": {
        "dev": "-Xms256M -Xmx512M",
        "stage": null,
        "prod": "-Xms1G -Xmx2G"
      },
      "type": "java_opts"
    },
    {
      "default": false,
      "envOverride": {
        "dev": null,
        "stage": true,
        "prod": true
      },
      "type": "empty_dir_memory"
    }
  ],
  "version": 0
}
