POST http://localhost:8193/api/v1.0/application
accept: application/json
Content-Type: application/json

{
  "id": "anticor-liveramp-audience-file-upload",
  "projectId": "anticor-liveramp",
  "name": "Anticor LiveRamp Audience File Upload",
  "envConf": [
    {
      "envKey": "ENV_KEY_BOOLEAN_VALUE",
      "type": "boolean",
      "default": {
        "value": true
      },
      "envOverride": {
        "dev": {
          "value": false
        },
        "stage": {
          "value": false
        },
        "prod": {
          "value": true
        }
      }
    },
    {
      "envKey": "ANTICOR_LIVERAMP_AUDIENCE_FILE_UPLOAD_TENANT_PARALLELISM",
      "type": "integer",
      "default": {
        "value": 2
      },
      "envOverride": {
        "dev": {
          "value": 1
        },
        "stage": null,
        "prod": {
          "value": 5
        }
      }
    },
    {
      "envKey": "ANTICOR_LIVERAMP_AUDIENCE_FILE_UPLOAD_INTERVAL_NOT_OFTEN_THAN_MINUTES",
      "type": "integer",
      "default": {
        "value": 1440
      },
      "envOverride": {
        "dev": {
          "value": 15
        },
        "stage": {
          "value": 180
        },
        "prod": null
      }
    }
  ],
  "deployConf": [
    {
      "default": 200,
      "envOverride": {
        "dev": null,
        "stage": null,
        "prod": 500
      },
      "type": "request_cpu"
    },
    {
      "default": 1024,
      "envOverride": {
        "dev": null,
        "stage": 2048,
        "prod": 8096
      },
      "type": "request_ram"
    }
  ],
  "version": 1
}
