POST http://localhost:8193/api/v1.0/project
accept: application/json
Content-Type: application/json

{
  "id": "legacy-anticor-liveramp-3",
  "name": "Legacy Anticor Liveramp 3",
  "envConf": [
    {
      "envKey": "POSTGRES_PORT",
      "default": null,
      "type": "string",
      "envOverride": {
        "dev": {
          "value": "5435"
        }
      }
    },
    {
      "envKey": "PULSAR_HOST",
      "default": null,
      "type": "string",
      "envOverride": {
        "dev": {
          "value": "pulsar.legacy.anticor.liveramp.dev"
        },
        "stage": {
          "value": "pulsar.legacy.anticor.liveramp.stage"
        }
      }
    },
    {
      "envKey": "LIVERAMP_DB_PORT",
      "type": "integer",
      "default": {
        "value": 5432
      },
      "envOverride": {
        "dev": null,
        "stage": null,
        "prod": null
      }
    },
    {
      "envKey": "LIVERAMP_DB_SCHEMA",
      "type": "string",
      "default": {
        "value": "liveramp"
      },
      "envOverride": {
        "dev": null,
        "stage": null,
        "prod": null
      }
    }
  ],
  "deployConf": [
    {
      "default": 1,
      "envOverride": null,
      "type": "replica"
    },
    {
      "default": 100,
      "envOverride": {
        "dev": 50,
        "stage": null,
        "prod": 200
      },
      "type": "request_cpu"
    }
  ],
  "version": 1
}
